//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MI_primera_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provedores
    {
        public int Id_Provedor { get; set; }
        public string Nombre_Porvedores { get; set; }
        public Nullable<decimal> Precio_Porvedores { get; set; }
    }
}
